### ISSUE TITLE
Update documentation for `v0.6.0` release

### ISSUE THREAD

**Issue by adrhill** [adrhill/ExplainableAI.jl#133]
Currently, the following things can be improved or are missing documentation:
- [x] input augmentations: `NoiseAugmentation`, `InterpolationAugmentation`
- [x] usage of `LayerMap` and `show_layer_indices` introduced in #131
- [x] LRP keyword `flatten` and performance benefits
- [x] LRP model canonization 
- [x] Update section "How it works internally" for #119
- [x] Update "Model checks for humans" for #119 
- [x] ~Use [DocumenterCitations.jl](https://github.com/JuliaDocs/DocumenterCitations.jl)~
- [x] #64
